### ISSUE TITLE
Default value of decode_utf8 ?

### ISSUE THREAD

**Issue by bbkr** [makamaka/Text-CSV#15]
Param description says that: "This attributes defaults to TRUE."

However later doc says

```
$csv = Text::CSV->new ();

is equivalent to

 $csv = Text::CSV->new ({
    ...
    decode_utf8         => 0,
```

BTW: also "This attributes" should be changed to "This attribute".

**Comment by charsbar** [comment]
Fixed by the above commit from SkySymbol.
