### ISSUE TITLE
Leading Zero problem with \r\n

### ISSUE THREAD

**Issue by NicoHood** [makamaka/Text-CSV#29]
Hello,
I try to import CSV files with values like “001”. This works as long as I use \n as linefeed. With a windows linefeed \r\n it does not work (results in “1”).
I tried several things to solve this problem, but nothing seems to work. Maybe I miss something obvious?

Here is a quick excerpt from my code (to see what settings I am using):
```perl
	# Create CSV Object
	# http://perlmaven.com/how-to-read-a-csv-file-using-perl
	my $csv = Text::CSV->new ({
		binary		=> 1,
		auto_diag => 1,
		sep_char	=> $myCSVSeparator,
	});

	# Open CSV File
	print "Opening file \"$file\" for overview.\n" if DEBUG1;
	open(my $data, '<:encoding(utf8)', $file) or die "Could not open '$file' $!\n";
	
	# Get header data
	my @headerData = $csv->column_names ($csv->getline ($data));
	my $colCount = @headerData;
	
	# Get table data
	my $tableDataHashRef = $csv->getline_hr_all ($data);
	my $rowCount = scalar(@$tableDataHashRef);
```

**Comment by charsbar** [comment]
Hi. I couldn't reproduce this. Could you show us which version of Text::CSV_PP you are using, and if it is not the latest (1.33), please make sure to upgrade it first and see if the issue still lingers for you?

**Comment by NicoHood** [comment]
I, I cannot tell which version I used at that time, the one that was available via CPAN probably. I am also not anymore involved in that project, so I am sorry that I cannot provide any further details than that.

**Comment by charsbar** [comment]
OK. Thanks.
