### ISSUE TITLE
Error during parsing field that contains comma and escaped quote (')

### ISSUE THREAD

**Issue by und3f** [makamaka/Text-CSV#32]
Hi,

here is the example:

``` perl
my $csv = Text::CSV->new ({ escape_char => "\\", allow_loose_escapes => 1, auto_diag=>1 });
$csv->parse (q("error, a\' string"));
```

Returns:

```
# CSV_PP ERROR: 2027 - EIQ - Quoted field not terminated
```

This fields is parsed as expected if remove either comma or escape character.

**Comment by Tux** [comment]
What version of Text::CSV_PP and/or Text::CSV_XS did you use? For me both Text::CSV_PP-1.33 and Text::CSV_XS-1.25 do not return that error.

**Comment by und3f** [comment]
I use version 1.33 of Text::CSV_PP.
````
$ perl -MV=Text::CSV,Text::CSV_PP,Text::CSV_XS
Text::CSV
        /home/user/perl5/lib/perl5/Text/CSV.pm: 1.33
Text::CSV_PP
        /home/user/perl5/lib/perl5/Text/CSV_PP.pm: 1.33
Text::CSV_XS
        Not found
$ perl -MText::CSV                  
my $csv = Text::CSV->new ({ escape_char => "\\", allow_loose_escapes => 1, auto_diag=>1 });
$csv->parse (q("error, a\' string"));
# CSV_PP ERROR: 2027 - EIQ - Quoted field not terminated
````

**Comment by charsbar** [comment]
Thanks for your report and extra input. I've confirmed it still happens with Text::CSV_PP 1.33. I'm supposing it's probably because the proper regexp differs when the escape char is "\\" or not. Give me a bit more time as there're several regexen to test depending on the options.

**Comment by charsbar** [comment]
I can't say since which commit, but Text::CSV_PP is totally refactored and doesn't have this issue as of 1.91. Thanks.
