### ISSUE TITLE
Can't write non-ASCII symbols

### ISSUE THREAD

**Issue by pavelsr** [makamaka/Text-CSV#34]
Please check an example

```perl
my $file = "test.csv";
my $csv = Text::CSV->new({ eol => "\n" }) or die "Cannot use CSV: ".Text::CSV->error_diag ();
open my $fh, ">", $file or die "$file.csv: $!";
my $a = [ 'a', 'б' ];
$csv->print($fh, $a);
close $fh or die "$!";
```
is working and produces

```bash
$ cat test.csv 
a,b
```

But if we try to write non-ASCII symbols like

```perl
my $a = [ 'a', 'б' ];
$csv->print($fh, $a);
```

output csv will empty

**Comment by charsbar** [comment]
This is because its default behavior is to only accept ASCII characters as the doc clearly states. See https://metacpan.org/pod/Text::CSV#Embedded-newlines and add ```binary => 1``` into ```Text::CSV->new({ })```.
