### ISSUE TITLE
module() (and is_xs()/is_pp()) don't work 

### ISSUE THREAD

**Issue by hartzell** [makamaka/Text-CSV#36]
With Text:CSV(1.95) and Text::CSV_XS(1.34) installed via `cpan` (tests pass) using perl v5.24.1, the following program complains about the use of an unintialized value.

```perl
use strict;
use warnings;

use Text::CSV;

my $csv = Text::CSV->new();

print $csv->module(), "\n";
```

```sh
$ perl foo.pl
Use of uninitialized value in print at foo.pl line 8.

$
```

The `module` sub relies on an `_MODULE` attribute, which neither `Text::CSV_PP` nor `Text::CSV_XS` seem to set.

I noticed this while trying to convince myself that I was, in fact, using the XS implementation.

**Comment by charsbar** [comment]
Thanks!
