### ISSUE TITLE
'csv' function missing from SYNOPSIS

### ISSUE THREAD

**Issue by akarelas-pt** [makamaka/Text-CSV#39]
The csv function is a lot easier to use than the OO interface, and helps produce smaller, neater code. Text::CSV_XS has it in the SYNOPSIS section of the module's POD. Couldn't you also include it there? I didn't know of the function's existence or usefulness for many years because of its absence from the SYNOPSIS, where I would easily have seen how much easier things become when using it. I know people who have written their own wrapper functions to make Text::CSV easier to use, because they didn't know of the csv function! It would help everyone I think, if the csv function were included in the SYNOPSIS.

Thanks.

**Comment by charsbar** [comment]
Shipped 1.98 with the same SYNOPSIS section as the latest Text::CSV_XS. Thanks.
