### ISSUE TITLE
Q: Is there an option to turn off escape char if whole string is not quoted?

### ISSUE THREAD

**Issue by KES777** [makamaka/Text-CSV#44]
Hi. I have bank statements from different banks. One send correct CSV, but other not:

    "АТ ""ОТП БАНК""";nextvalue

    АТ КБ "ПРИВАТБАНК";nextvalue

I doubt that they will change something. So I ask about an option which will allow to not count `"`  char at second line as escape char if cell value is not quoted.

**Comment by charsbar** [comment]
```allow_loose_quotes```, maybe? (cf. https://metacpan.org/pod/Text::CSV_XS#allow_loose_quotes )

If this doesn't work for you, and if you are really sure there's nothing that helps you after you read the manual, could you please ask H.Merijn Brand, the maintainer of [Text::CSV_XS](https://github.com/Tux/Text-CSV_XS) for help? Text::CSV is just a wrapper of it.
