### ISSUE TITLE
Offer option to not put empty columns into hashes created

### ISSUE THREAD

**Issue by jidanni** [makamaka/Text-CSV#48]
Idea: offer an option to not put empty columns into hashes created.
```
use Text::CSV qw( csv );
my $aoh = csv( in => "data.csv", headers => "auto" );
```
is great, but if I want a smaller hash, I must then do:
```
for my $row (@$aoh) {
    for my $column ( keys %$row ) {
        delete $row->{$column} unless length $row->{$column};
    }
}
```
Therefore please perhaps also offer:
```
my $aoh = csv( in => "data.csv", headers => "auto", skip_empty_columns => 1 );
```
so people can get a smaller hash from the start.

> What's the big deal?

Could reduce the size of the hash by e.g., 99% in certain cases.

> Well just do that delete stuff yourself like you said.

But the big bloated hash has has already been created...
we still haven't reduced at least initial memory usage. 

Version: 2.00-1

**Comment by charsbar** [comment]
Test::CSV(_PP) is just a wrapper/fallback module of Text::CSV_XS. Could you please discuss this issue at https://github.com/Tux/Text-CSV_XS/issues first?

**Comment by jidanni** [comment]
OK. Maybe put a warning in the bug report template.

**Comment by Tux** [comment]
If I read the original statement, I read it as to delete complete columns if none of the rows in that column have content (definable by the user).
Personally I do not think this is feasible as described, as one can only detect if a column is empty after parsing the whole stream.
But if you want to do this on a per-record base, watch ...
``` perl
use 5.14.2;
use warnings;

use Data::Peek;
use Text::CSV_XS qw( csv );

my $strip = shift;

my @h;
DDumper csv (in => *DATA, headers => "auto", kh => \@h, on_in => sub {
    $strip or return;
    delete $_{$_} for grep { !length $_{$_} } @h;
    });

__END__
a,b,c,d
1,2,3,4
1,,3,4
1,2,,4
1,2,3,
1,,,
,,,4
,,3,
```
``` sh
$ perl issuepp48.pl 0
[
    {   a                => '1',
        b                => '2',
        c                => '3',
        d                => '4'
        },
    {   a                => '1',
        b                => '',
        c                => '3',
        d                => '4'
        },
    {   a                => '1',
        b                => '2',
        c                => '',
        d                => '4'
        },
    {   a                => '1',
        b                => '2',
        c                => '3',
        d                => ''
        },
    {   a                => '1',
        b                => '',
        c                => '',
        d                => ''
        },
    {   a                => '',
        b                => '',
        c                => '',
        d                => '4'
        },
    {   a                => '',
        b                => '',
        c                => '3',
        d                => ''
        }
    ]
```
``` sh
$ perl issuepp48.pl 1
[
    {   a                => '1',
        b                => '2',
        c                => '3',
        d                => '4'
        },
    {   a                => '1',
        c                => '3',
        d                => '4'
        },
    {   a                => '1',
        b                => '2',
        d                => '4'
        },
    {   a                => '1',
        b                => '2',
        c                => '3'
        },
    {   a                => '1'
        },
    {   d                => '4'
        },
    {   c                => '3'
        }
    ]
```
Callbacks are your friend. FYI this is not done at the end, but for each record, so this is doing exactly what you state in your quest.

**Comment by jidanni** [comment]
Hmmm, maybe this is worth documenting as a recipe, for folks who might want to do that. Perhaps using $csv->getline, if it somehow can avoid allocating things that need to be deleted later. But I'll close this for now. Thanks.
